services:
  next-app:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      args:
        MONGO_URI: ${MONGO_URI}
        NEXT_PUBLIC_TWITTER_LINK: ${NEXT_PUBLIC_TWITTER_LINK}
        NEXT_PUBLIC_GITHUB_LINK: ${NEXT_PUBLIC_GITHUB_LINK}
        NEXT_PUBLIC_LINKEDIN_LINK: ${NEXT_PUBLIC_LINKEDIN_LINK}
        NEXT_PUBLIC_RESUME_LINK: ${NEXT_PUBLIC_RESUME_LINK}
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        SKIP_ENV_VALIDATION: 1
        UPLOADTHING_SECRET: ${UPLOADTHING_SECRET}
        UPLOADTHING_APP_ID: ${UPLOADTHING_APP_ID}
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_URL: ${AUTH_URL}
    container_name: portfolio
    ports:
      - "${PORT:-3000}:3000"
